<a href="https://colab.research.google.com/github/tireless-22/4rthSemPythonLab/blob/main/AI_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AI LAB

WEEK1


In [20]:
import numpy as np

import pandas as pd

a. To generate an array of random numbers from a normal distribution for the array of a
given shape

In [13]:
a=np.random.randint(1,100,20)
# Here we generated 20 values in between the 1 and 100
print(a)

[37 32  3 82  8 66 39 40 77 74 82 80 28 14 92 73 74 98  2 31]


b. Implement Arithmetic operations on two arrays (perform broadcasting also

In [8]:
normalList_a=[1,2,3,4]
normalList_b=[5,6,7,8]
# a is list here
numpyArray_a=np.array(normalList_a)
numpyArray_b=np.array(normalList_b)
# print(type(numpyArray_a))

# addition
print("addition")
print(numpyArray_a+numpyArray_b)

# substraction
print("substraction")
print(numpyArray_a-numpyArray_b)

# multiplication
print("multiplication")
print(numpyArray_a*numpyArray_b)

# division
print("division")
print(numpyArray_a/numpyArray_b)



addition
[ 6  8 10 12]
substraction
[-4 -4 -4 -4]
multiplication
[ 5 12 21 32]
division
[0.2        0.33333333 0.42857143 0.5       ]


c Find minimum, maximum, mean in a given array. ( in both the axes )

In [11]:
a=np.random.randint(10,30,20)
print("generated array")
print(a)
print("minimum")
print(a.min())
print("maximum")
print(a.max())
print("mean")
print(a.mean())

[29 28 11 19 24 13 19 24 10 23 20 29 23 21 11 10 23 15 28 18]
minimum
10
maximum
29
mean
19.9


d. Implement np.arange and np.linspace functions. 

In [19]:
# Arrange


# first value is start and second is end
# 3rd one is jump
# 1st value is inclusive
# 2nd value is exclusive
a=np.arange(10)
print(a)
print()
b=np.arange(1,51,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [17]:
# linespace

# both the start and end are inclusive
# first value is starting value and
# second value is the ending value
# third one is no of samples,but it is optional
# defaultly it is set to 50 samples
# to know the step of the values,find the difference between the consecutive values

a=np.linspace(2,9)
print("created array")
print(a)
print()
print("step in the array")
print(a[1]-a[0])


created array
[2.         2.14285714 2.28571429 2.42857143 2.57142857 2.71428571
 2.85714286 3.         3.14285714 3.28571429 3.42857143 3.57142857
 3.71428571 3.85714286 4.         4.14285714 4.28571429 4.42857143
 4.57142857 4.71428571 4.85714286 5.         5.14285714 5.28571429
 5.42857143 5.57142857 5.71428571 5.85714286 6.         6.14285714
 6.28571429 6.42857143 6.57142857 6.71428571 6.85714286 7.
 7.14285714 7.28571429 7.42857143 7.57142857 7.71428571 7.85714286
 8.         8.14285714 8.28571429 8.42857143 8.57142857 8.71428571
 8.85714286 9.        ]

step in the array
0.1428571428571428


e. Create a pandas series from a given list


In [24]:
normalList_a=np.linspace(2,9)

numpyArray_a = pd.Series(normalList_a)

print(numpyArray_a)

0     2.000000
1     2.142857
2     2.285714
3     2.428571
4     2.571429
5     2.714286
6     2.857143
7     3.000000
8     3.142857
9     3.285714
10    3.428571
11    3.571429
12    3.714286
13    3.857143
14    4.000000
15    4.142857
16    4.285714
17    4.428571
18    4.571429
19    4.714286
20    4.857143
21    5.000000
22    5.142857
23    5.285714
24    5.428571
25    5.571429
26    5.714286
27    5.857143
28    6.000000
29    6.142857
30    6.285714
31    6.428571
32    6.571429
33    6.714286
34    6.857143
35    7.000000
36    7.142857
37    7.285714
38    7.428571
39    7.571429
40    7.714286
41    7.857143
42    8.000000
43    8.142857
44    8.285714
45    8.428571
46    8.571429
47    8.714286
48    8.857143
49    9.000000
dtype: float64


f. Create pandas series with data and index and display the index values

In [36]:
dff=pd.DataFrame()
n=int(input("enter the no of columns"))
m=int(input("no of rows"))

lower_limit=int(input("enter_lower_limit"))
upper_limit=int(input("enter_right_limit"))


temp=65
for i in range(m):
  dff[chr(temp+i)]=np.random.randint(lower_limit,upper_limit,n)


print(dff)

enter the no of columns10
no of rows10
enter_lower_limit1
enter_right_limit100
    A   B   C   D   E   F   G   H   I   J
0  25  41  50  46  64   9  48  97  81  46
1  56  47  79  24  52   1  22  20   9  38
2  82  33  37  83  93   5  43  93  56  68
3  14  51  28  42  67  65  73  83   4  33
4  79  59  93  19  73  31   4  10  65  43
5   9  79  89  48  96  95  11  82  70  34
6  74  70  90  56  63  81  44  83  24  90
7  21  53   9  50  11  82  30  82  48  68
8  48  84  18  47  23  61  93  57  75  71
9  47  95  84  98  36  96  99  44  27  80


g. Create a data frame with columns at least 5 observations

i. Select a particular column from the DataFrame

ii. Summarize the data frame and observe the stats of the DataFrame created

iii. Observe the mean and standard deviation of the data frame and print the values. 


In [51]:
# use that dff here

randColIndex=np.random.randint(0,n)
print("picked random column number",randColIndex)
print()

print("printing that picked random column")

print(dff[chr(65+randColIndex)])



picked random column number 9

printing that picked random column
0    46
1    38
2    68
3    33
4    43
5    34
6    90
7    68
8    71
9    80
Name: J, dtype: int64


In [49]:
print("description about the data that we have")
print()

print(dff.describe())

description about the data that we have

               A          B          C          D          E          F  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.500000  61.200000  57.700000  51.300000  57.800000  52.600000   
std    27.346542  20.104173  32.883802  23.902812  27.867943  37.818867   
min     9.000000  33.000000   9.000000  19.000000  11.000000   1.000000   
25%    22.000000  48.000000  30.250000  43.000000  40.000000  14.500000   
50%    47.500000  56.000000  64.500000  47.500000  63.500000  63.000000   
75%    69.500000  76.750000  87.750000  54.500000  71.500000  81.750000   
max    82.000000  95.000000  93.000000  98.000000  96.000000  96.000000   

               G          H          I          J  
count  10.000000  10.000000  10.000000  10.000000  
mean   46.700000  65.100000  45.900000  57.100000  
std    32.625995  30.892106  28.057283  20.652952  
min     4.000000  10.000000   4.000000  33.000000  
25%    24.000000  47.25

In [50]:
print("printing means")
print()
print()
print(dff.mean())

printing means


A    45.5
B    61.2
C    57.7
D    51.3
E    57.8
F    52.6
G    46.7
H    65.1
I    45.9
J    57.1
dtype: float64
