<a href="https://colab.research.google.com/github/tireless-22/4rthSemPythonLab/blob/main/AI_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AI LAB

WEEK1


In [3]:
import numpy as np
# imported numpy as np

a. To generate an array of random numbers from a normal distribution for the array of a
given shape

In [13]:
a=np.random.randint(1,100,20)
# Here we generated 20 values in between the 1 and 100
print(a)

[37 32  3 82  8 66 39 40 77 74 82 80 28 14 92 73 74 98  2 31]


b. Implement Arithmetic operations on two arrays (perform broadcasting also

In [8]:
normalList_a=[1,2,3,4]
normalList_b=[5,6,7,8]
# a is list here
numpyArray_a=np.array(normalList_a)
numpyArray_b=np.array(normalList_b)
# print(type(numpyArray_a))

# addition
print("addition")
print(numpyArray_a+numpyArray_b)

# substraction
print("substraction")
print(numpyArray_a-numpyArray_b)

# multiplication
print("multiplication")
print(numpyArray_a*numpyArray_b)

# division
print("division")
print(numpyArray_a/numpyArray_b)



addition
[ 6  8 10 12]
substraction
[-4 -4 -4 -4]
multiplication
[ 5 12 21 32]
division
[0.2        0.33333333 0.42857143 0.5       ]


c Find minimum, maximum, mean in a given array. ( in both the axes )

In [11]:
a=np.random.randint(10,30,20)
print("generated array")
print(a)
print("minimum")
print(a.min())
print("maximum")
print(a.max())
print("mean")
print(a.mean())

[29 28 11 19 24 13 19 24 10 23 20 29 23 21 11 10 23 15 28 18]
minimum
10
maximum
29
mean
19.9


d. Implement np.arange and np.linspace functions. 

In [ ]:
# Arrange


# first value is start and second is end
# 3rd one is jump
# 1st value is inclusive
# 2nd value is exclusive
a=np.arange(10)
print(a)
b=np.arange(1,51,2)
print(b)

In [17]:
# linespace

# both the start and end are inclusive
# first value is starting value and
# second value is the ending value
# third one is no of samples,but it is optional
# defaultly it is set to 50 samples
# to know the step of the values,find the difference between the consecutive values

a=np.linspace(2,9)
print("created array")
print(a)
print()
print("step in the array")
print(a[1]-a[0])


created array
[2.         2.14285714 2.28571429 2.42857143 2.57142857 2.71428571
 2.85714286 3.         3.14285714 3.28571429 3.42857143 3.57142857
 3.71428571 3.85714286 4.         4.14285714 4.28571429 4.42857143
 4.57142857 4.71428571 4.85714286 5.         5.14285714 5.28571429
 5.42857143 5.57142857 5.71428571 5.85714286 6.         6.14285714
 6.28571429 6.42857143 6.57142857 6.71428571 6.85714286 7.
 7.14285714 7.28571429 7.42857143 7.57142857 7.71428571 7.85714286
 8.         8.14285714 8.28571429 8.42857143 8.57142857 8.71428571
 8.85714286 9.        ]

step in the array
0.1428571428571428


e. Create a pandas series from a given list


f. Create pandas series with data and index and display the index values

g. Create a data frame with columns at least 5 observations
i. Select a particular column from the DataFrame
ii. Summarize the data frame and observe the stats of the DataFrame created
iii. Observe the mean and standard deviation of the data frame and print the values. 
