<a href="https://colab.research.google.com/github/tireless-22/4rthSemPythonLab/blob/main/PythonLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PYTHON PROGRAMMING LAB 
(19CT1106)

K.NAVEEN KARTHIK REDDY 
(19131A0498)

LIST OF EXPERIMENTS:


#######################################################################################################

WEEK1 Input and output


(a) Print the "Python" for 1, print "Day - 1" for 2. By changing the variable "look" for
each statement


In [ ]:
look=int(input("enter 0 or 1 only  "))
if (look==0):
  print("Python")
elif(look==1):
  print("Day-1")
else:
  print("Wrong entry ! please enter o or 1 only")    

enter 0 or 1 only  1
Day-1


(b)Create a variable "number" and assign an Integer to the number. Check the assigned
Integer is "Positive" or "Negative".


In [ ]:
# SOLUTION 1

number=int(input("enter any number   "))
if(number>0):
  print("Given number is possitive")
elif(number<0):
  print("Given number is negative")
else:
  print("Given number is neither possitive nor negative")


#SOLUTION 2 
# ans="possitive" if int(input("enter any number   "))>0 else "negative"
# print(ans)  

enter any number   -7
Given number is negative


(c) Write a program to find the largest element among three Numbers

In [ ]:
# solutions 1
# a=int(input())
# b=int(input())
# c=int(input())
# if a>b and a>c:
#   print(a)
# elif b>a and b>c:
#   print(b)  
# else:
#   print(c)

  
# solution 2
a,b,c=input().split()
largestNumber=a if a>b and a>c else b if b>c else c
print(largestNumber)

5 1 4
5


(d) Write a program to print the sum of all the even numbers in the range 1 - 50 and print
the even sum.


In [ ]:
# solution 1
# evenSum=0
# for i in range(1,51):
#   if (i%2==0):
#     evenSum+=i
# print(evenSum)

#solution 2
from functools import *
print(reduce(lambda a,b:a+b,[x for x in range(1,51) if x%2==0]))

650


(e) Write a Program to display all prime numbers within an interval of 20 and 50.


In [ ]:
from math import *
def checkIfPrime(num):
  
  for i in range(2,int(sqrt(num))+1):
    if num%i==0:
      break
  else:
    print(num) 
for i in range(20,51):
  checkIfPrime(i)
 

23
29
31
37
41
43
47


#######################################################################################################

WEEK2 Variables and Functions

a. Write a program to swap two numbers without using a temporary variable.


In [ ]:
a,b=input().split()
print("before")
print(a,b)
a,b=b,a
print("after")
print(a,b)

1 9
before
1 9
after
9 1


b. Write a program to define a function with multiple return values

In [ ]:
def add_sub(a,b):
  sum=a+b
  sub=a-b
  return sum,sub
sum,sub=add_sub(4,2)
print(sum,sub)

6 2


c. Write a program which creates an adder given a value (Use only lambda).


In [ ]:
A = 0
B = 1
C = 1

# half adder
# sum=a xor b
# carry=a and b

# [int(x) for x in input().split()]
# full adder 
# sum=a xor b xor c
# carry=a and b+ c and(a xor b)


half_adder_sum = lambda a, b : a ^ b
half_adder_carry = lambda a, b : a & b
full_adder_sum = lambda a, b, c : (a ^ b) ^ c
full_adder_carry = lambda a, b, c : (a& b)+(c& (a ^b))


print(half_adder_sum(A, B))
print(half_adder_carry(A, B))
print(full_adder_sum(A,B,C))
print(full_adder_carry(A,B,C))

1
0
0
1


d. Write a program to define a function using default arguments.

In [ ]:
def default_args(a="python",b="lab"):
  print(a)
  print(b)
default_args()
default_args("gvp","vizag")

python
lab
gvp
vizag


#######################################################################################################

WEEK3 Loops and conditionals



a. Write a program to print the following patterns using loop:
*
**
***
****

In [ ]:
for i in range(1,5):
  print("*"*i)

*
**
***
****


b. Write a program to print multiplication tables of 8, 15, 69.


In [ ]:
def tables(n,limit):
  for i in range(1,limit+1):
    print(n,"✖",i,"=",n*i)
  print()  

NoOfTimes=10
tables(8,NoOfTimes)
tables(15,NoOfTimes)
tables(69,NoOfTimes)

8 ✖ 1 = 8
8 ✖ 2 = 16
8 ✖ 3 = 24
8 ✖ 4 = 32
8 ✖ 5 = 40
8 ✖ 6 = 48
8 ✖ 7 = 56
8 ✖ 8 = 64
8 ✖ 9 = 72
8 ✖ 10 = 80

15 ✖ 1 = 15
15 ✖ 2 = 30
15 ✖ 3 = 45
15 ✖ 4 = 60
15 ✖ 5 = 75
15 ✖ 6 = 90
15 ✖ 7 = 105
15 ✖ 8 = 120
15 ✖ 9 = 135
15 ✖ 10 = 150

69 ✖ 1 = 69
69 ✖ 2 = 138
69 ✖ 3 = 207
69 ✖ 4 = 276
69 ✖ 5 = 345
69 ✖ 6 = 414
69 ✖ 7 = 483
69 ✖ 8 = 552
69 ✖ 9 = 621
69 ✖ 10 = 690



#######################################################################################################

WEEK4 Strings

a. Write a program to find the length of the string without using any library functions


In [ ]:
def length(string):
  length=0
  for i in string:
    length+=1
  print(length)

length("GVPCE")    

5


b. Write a program to check if two strings are anagrams or not.


In [ ]:
def anagram(s1,s2):
  s1=sorted(s1.lower())
  s2=sorted(s2.lower())
  l1=[]
  l2=[]
  for i in s1:
    if i!=" ":
      l1.append(i)
  for i in s2:
    if i!=" ":
      l2.append(i)  
  return l1==l2      
  
a=input()
b=input()
print(anagram(a,b))

hlj
lbkjbn
False


c. Write a program to check if the substring is present in a given string or not. (use regular
expressions)

In [ ]:
# import re

# Str = input("enter the string   ")
# subStr=input("enter the substring   ")
# x = re.findall(subStr, Str)
# if(len(x)!=0):
#   print("substring is present in a given string ")
# else:
#   print("not here")    


strr = input("enter the string   ")
subStr=input("enter the substring   ")
if (strr.count(subStr)==0):
  print("not here")
else:
  print("present")  



enter the string   hello this is
enter the substring   is
present


#######################################################################################################

WEEK5 lists

a. Write a program to perform the given operations on a list:
i. add ii. insert iii. slicing


In [ ]:
def add(listt,value):
  listt.append(value)
  print(listt)

def insert(listt,indexNumber,value):
  listt[indexNumber]=value
  print(listt)

def slicing(listt,startingIndex,endingIndex):

  slicedList=listt[startingIndex:endingIndex:]
  print(slicedList)

listt=[2,3,2,3,43,4]


slicing(listt,3,6)

insert(listt,4,3333)
add(listt,444)



[3, 43, 4]
[2, 3, 2, 3, 3333, 4]
[2, 3, 2, 3, 3333, 4, 444]


b. Write a program to perform any 5 built-in functions by taking any list

In [ ]:
l=[2,5,4,5,3,2,8]
print("maximum number is : ",max(l))
print("minimum number is : ",min(l))
print("added 333 to the given list : ",l.append(333))
print("deleted 333 from the given list : ",l.pop())
# pop will delete the last element added to the list
print("sorted list :  ",l.sort())

maximum number is :  8
minimum number is :  2
added 333 to the given list :  None
deleted 333 from the given list :  333
sorted list :   None


c. Write a program to get a list of the even numbers from a given list of numbers.(use
only comprehensions)


In [ ]:
l=eval(input())
l=[x for x in l if int(x)%2==0 ]
print(l)
# [2,5,4,5,3,2,8]

[2,5,4,5,3,2,8]
[2, 4, 2, 8]


In [ ]:
a=list(map(int,input('enter a list').split()))
b=list(map(int,input('enter a list').split()))
c=list(map(int,input('enter a list').split()))


d=[a,b,c]
e=[len(a),len(b),len(c)]
n=max(e)
for j in range(0,n):
  for i in range(0,len(d)):
      if(len(d[i])>j):
          print(d[i][j],end=" ")


enter a list33 53 234 2523 234
enter a list234 5234 2425
enter a list242 242 53
33 234 242 53 5234 242 234 2425 53 2523 234 

#######################################################################################################

WEEK6 TUPLES

a. Write a program to create tuples (name, age, address, college) for at least two 
members and concatenate the tuples and print the concatenate tuples

In [ ]:
t=()
for i in range(int(input("enter the no of students      "))):
  name=input()
  age=int(input())
  ad=input()
  clg=input()
  t1=name,age,ad,clg
  t+=t1
print(t)


enter the no of students      2
df
23
sdf
sd
asdf
34
sdf
asdf
('df', 23, 'sdf', 'sd', 'asdf', 34, 'sdf', 'asdf')


b. Write a program to return the top 'n' most frequently occurring chars and their respectivecounts.
e.g. aaaaaabbbbcccc,  should return [(a 6) (b 4)]

In [ ]:
# strn=input()

# solution 1 using tuples 

# temp=strn[0]
# count=0
# l=[]
# for i in range(len(strn)):
#   if strn[i]==temp:
#     count+=1
#     temp=strn[i]
#   else:
#     l.append((temp,count))
#     count=0
#     temp=strn[i]
#     count+=1
#   if (i==len(strn)-1):
#     l.append((temp,count))    
# print(l)



# # solution 2 using dictionary 


# dictt={}
# for x in strn:
#   if x in dictt.keys():
#     dictt[x]+=1
#   else:
#     dictt[x]=1 
# print(dictt)    




# solution 3 using list
# strn="aaaabbbcccccaaaaabbbcccca"
# n=2


strn=input("enter the string")
n=int(input("enter the number of values"))
l,l1 = [],[]
for i in strn:
  if(i==" "):
      continue
  flag = False
  for x in range(len(l)):
    if i in l[x][0]:
      l[x][1] += 1
      flag = True
  if not flag:
    l.append([i,1])
    flag = False
l1=sorted(l,key=lambda x:x[1],reverse=True)
tup = []
for i in range(n):
  tup.append((l1[i][0],l1[i][1]))
print(tup)

enter the stringnaveen karthik reddy
enter the number of values5
[('e', 3), ('n', 2), ('a', 2), ('k', 2), ('r', 2)]


#######################################################################################################

WEEK7 SETS

a. Write a program to count the number of vowels in a string (No control flow allowed).


In [ ]:
strn = input()
result = len(list(filter(lambda x: x,list(map(lambda a: a in ['a','A','e','E','i','I','o','O','u','U'],list(strn))))))
print(result)
# "Words are thought of as the smallest meaningful unit of speech"

this is python lab
4


b. Write a program that displays which letters are present in both strings.


In [ ]:
s1=input()
s2=input()
s=set()
for i in s1:
  if (i in s2 and i!=" "):
    s.add(i)
print(s)

# "sample text"
# "Words are thought of as the smallest meaningful unit of speech"

"sample text"
"Words are thought of as the smallest meaningful unit of speech"
{'p', 'l', 'm', 's', 'a', '"', 't', 'e'}


c. Write a program to sort given list of strings in the order of their vowel counts.

In [ ]:
l=eval(input())
list_vowels=['a','A','e','E','i','I','o','O','u','U']
def noOfVowels(x):
  count=0
  for i in x:
    if(i in list_vowels ):
      count+=1
  return count      

l=sorted(l,key=noOfVowels)
print(l)

# ["Words", "are", "thought", "of", "as", "the" ,"smallest" ,"meaningful"]


["Words", "are", "thought", "of", "as", "the" ,"smallest" ,"meaningful"]
['Words', 'of', 'as', 'the', 'are', 'thought', 'smallest', 'meaningful']


#######################################################################################################

WEEK8 DICTIONARIES


a. Write a program to generate a dictionary that contains numbers (between 1 and n ) 
in the form of (x, x*x).


In [ ]:
dicc={}
for i in range(1,int(input("enter the value of n"))+1):
  dicc[i]=i*i
print(dicc)

enter the value of n5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


b. Write a program to check if a given key exists in a dictionary or not.


In [ ]:
dicc={1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
keyy=int(input("enter the value of key    "))
if keyy in dicc.keys():
  print("ss")
else:
  print("no")  


enter the value of key    8
no


c. Write a program to add a new key-value pair to an existing dictionary.

In [ ]:
dicc={1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
keyy=int(input("enter the new key    "))
valuee=int(input("enter the new value   "))
dicc[keyy]=valuee
print(dicc)


enter the new key    55
enter the new value   5555
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 55: 5555}


d. Write a program to sum all the items in a given dictionary

In [ ]:
# dicc={1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
dicc={}
for i in range(int(input("No of values"))):
  keyy=int(input("enter the key"))
  valuee=int(input("enter the values"))
  dicc[keyy]=valuee


print("sum of keys ",sum(dicc.keys()))
print("sum of values ",sum(dicc.values()))

No of values3
enter the key1
enter the values1
enter the key2
enter the values4
enter the key3
enter the values9
sum of keys  6
sum of values  14


#######################################################################################################

WEEK9 FILES


a. Write a program to sort words in a file and put them in another file. The output file 
should have only lower case words, so any upper case words from source must be 
lowered. (Handle exceptions)

In [ ]:
# this code is not for collab or jupyter notebook
# to execute this code ,follow the given steps

# step1: create a directory 
# step2: create python file in that directory
# step3:create 2 text files named "a.txt" and "b.txt" in the same directory
# step4:fill the "a.txt" will some sample lines
# step5:run the python file

f=open("a.txt","r")
lines=f.readlines()
l=[]
lll=[]
for line in lines:
    ll=line.split(" ")
    for i in ll:
        l.append(i)
l.sort()
for i in l:
    lll.append(i.lower())    
print(lll)
f1=open("b.txt","w")
s=" "
s=" ".join(lll)
f1.write(s)

b. Write a program to find the most frequent words in a text.(read from a text file)

In [ ]:
# this code is not for collab or jupyter notebook
# this code is to run in the local machines

# to execute this code ,follow the given steps

# step1: create a directory 
# step2: create python file in that directory
# step3:create 1 text files named "a.txt"  in the same directory
# step4:fill the "a.txt" will some sample lines
# step5:run the python file


f=open("a.txt","r")
lines=f.readlines()
l=[]
for line in lines:
    ll=line.split(" ")
    for i in ll:
        l.append(i)
temp=[]
l.sort()
print(l)
count=1
requiredWord=""
highestCount=1
for i in l:
    if i in temp:
        count+=1
        if(count>highestCount):
            highestCount=count
            print(highestCount)
            requiredWord=i
    else:
        temp.append(i)
        count=1
print(requiredWord," ==>repeated for ",highestCount," times")        

#######################################################################################################

WEEK 10 CLASSES

a. Write a Python class named Person with attributes name, age, weight (kgs), height 
(ft) and takes them through the constructor and exposes a method get_bmi_result() 
which returns one of "underweight", "healthy", "obese".

In [ ]:
class Person:
  def __init__(self, name, age,weight,height):
    self.name = name
    self.age = age
    self.weight=weight
    self.height=height
  def get_bmi_result(self):
    BMI=self.weight/(self.height*self.height)    
    if BMI>25:
      print("obese")
    elif BMI>18.5:
      print("healthy") 
    else:
      print("underweight") 
     
p1 = Person("underweight", 19,45,1.56)
p2 = Person("healthy", 19,65,1.8)
p3 = Person("obese", 19,65,1.56)
p1.get_bmi_result()
p2.get_bmi_result()
p3.get_bmi_result()

underweight
healthy
obese


b. Write a Python class named Circle constructed by a radius and two methods which 
will compute the area and the perimeter of a circle.

In [ ]:
class Circle:
  def __init__(self,radius):
    self.radius =radius
    
  def area(self):
    print("Area of the given circle of radius  ",self.radius,"  :",3.14*self.radius*self.radius)

  def perimeter(self):
    print("Perimeter of the given circle of radius  ",self.radius,"  :",2*3.14*self.radius)   
c1=Circle(5)
c1.area()   
c1.perimeter()  

c2=Circle(15)
c2.area()   
c2.perimeter()  


Area of the given circle of radius   5   : 78.5
Perimeter of the given circle of radius   5   : 31.400000000000002
Area of the given circle of radius   15   : 706.5
Perimeter of the given circle of radius   15   : 94.2


#######################################################################################################

NUMPY


In [ ]:
# use this commmand ,if it is not installed in your environment 
# for checking if it is installed or not , use (pip list) 
# if it is available you can see the name (numpy 1.21.0(some number)) the version is not at all important
# (pip install numpy)
import numpy as np
# creation of 1d array
arr1=np.array((1,3,43,4,53,3))
# creation of 2d arrays
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("printed 1d array","\n",arr1)
print("printed 2d array","\n",arr2)

# accessing of 1d array
print(arr1[2])

# accessing of 2d arrays
print(arr2[2][2])
print(arr2[2, 2])



printed 1d array 
 [ 1  3 43  4 53  3]
printed 2d array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
43
9
9


In [ ]:
import numpy as np

arr1=np.array((1,3,43,4,53,3))
np.append(arr1,5)
np.insert(arr,3,32) 
# print("given list",l)
# l.append(444)
# print("after appending",l)
# l.insert(3,555)
# print("after inserion",l)
# ll=l[::-1]
# print("after reversal",ll)

array([ 1,  3, 43, 32,  4, 53,  3])

WEEK 11 ARRAYS

a. Write a program to create, display, append, insert and reverse the order of the items in the array

In [ ]:
l=[2,32,423,233,4323,34532]
print("given list",l)
l.append(444)
print("after appending",l)
l.insert(3,555)
print("after inserion",l)
ll=l[::-1]
print("after reversal",ll)

given list [2, 32, 423, 233, 4323, 34532]
after appending [2, 32, 423, 233, 4323, 34532, 444]
after inserion [2, 32, 423, 555, 233, 4323, 34532, 444]
after reversal [444, 34532, 4323, 233, 555, 423, 32, 2]


b. Write a program to add, transpose and multiply two matrices.


In [ ]:
l1=[[1,4,2],[5,6,8],[10,2,3]]
l2=[[1,2,3],[1,2,3],[1,2,3]]
l=[]
def addd(l1,l2):
  for i in range(len(l1)):
    l.append([])
    for j in range(len(l1)):
      l[i].append(0)
      l[i][j]=l1[i][j]+l1[i][j]
  print("addition",l)

def trans(l1):
  l=[]
  i=0
  j=0
  for i in range(len(l1)):
    l.append([])
    for j in range(len(l1)):
      l[i].append(0)     
  for i in range(len(l1)):  
    for j in range(len(l1)): 
      l[j][i]=l1[i][j]   
  print("transpose",l)

def mull(l1,l2):
  l=[]
  for i in range(len(l1)):
    l.append([])
    for j in range(len(l1)):
      l[i].append(0)
  for i in range(len(l1)):
    for j in range(len(l2)):
      for k in range(len(l1)):
        l[i][j]+=l1[i][k]*l2[k][j]     
  print("multiplication",l)  

addd(l1,l2)
mull(l1,l2)
trans(l1)

addition [[2, 8, 4], [10, 12, 16], [20, 4, 6]]
multiplication [[7, 14, 21], [19, 38, 57], [15, 30, 45]]
transpose [[1, 5, 10], [4, 6, 2], [2, 8, 3]]


#######################################################################################################

WEEK12 GUI

Write a program to create a basic calculator using tkinter.


ADDITIONAL PROGRAMS

For GUI codes visit my ohter repo!!!

https://github.com/naveenkarthikreddy/GUI-Tkinter

1. Write a program to check whether a given number has an even number of 1's in its 
binary representation (No control flow allowed).


2. Write a program to implement user defined map() function.

In [ ]:
def sqr(a):
  return a*a
l=[1,2,3,4,5]
l=list(map(sqr,l))  
print(l)


[1, 4, 9, 16, 25]


3. Write a program to return a list in which duplicates are removed and the items are 
sorted from a given input list of strings.

4. Write a program to implement left binary search

5. Write a program to change days to hours, hours to minutes, and minutes to seconds 
using currying of composition of function.

6. Write a program to generate an infinite number of even numbers (Use generator)

7. Write a program to convert a given iterable into a list. (Using iterator)


8. Write a program that accepts a sequence of whitespace separated words as input and 
printsthe words after removing all duplicate words and sorting themalphanumerically


9. Given a string and a number k, find the kth non-repeating character in the string. 
Consider a large input string with lakhs of characters and a small character set. How 
to find the character by only doing only one traversal of input string?

e.g. input : str = hellopython k=3; output = y

Enter the start of range: 1
Enter the end of range: 50
650


   10. To add 'ing' at the end of a given string (length should be at least 3). If the givenstring already ends with 'ing' then add 'ly' instead. If the string length of the 
given string is less than 3, leave it unchanged.
e.g. input : 'abc' output : 'abcing' ; input : 'string' output : 'stringly'**bold text**